CREATE DATABASE IF NOT EXISTS `MYSQL_DATABASE_test`;
USE `MYSQL_DATABASE_test`;

GRANT CREATE ROUTINE, CREATE VIEW, ALTER, SHOW VIEW, CREATE, ALTER ROUTINE, EVENT, INSERT, SELECT, DELETE, TRIGGER, REFERENCES, UPDATE, DROP, EXECUTE, LOCK TABLES, CREATE TEMPORARY TABLES, INDEX ON `MYSQL_DATABASE_test`.* TO 'MYSQL_USER'@'%';
